language: node_js
node_js:
- '4'
script:
- echo nuffuink
before_install: npm install -g npm@'>=2.13.5'
deploy:
  provider: npm
  email: daniil.gentili.dg@gmail.com
  api_key:
    secure: gJWqE/qpk2E0Ljnlesjr2jfM02iG66ycQTKEPrDNdz5ugiV79Gz9lR69+UIxp9JhGZZ08vTF9d0BRBdX7Yo7ahICzuEuwmt6G/VQrBKNNN1Mo4qKeZpV56f7+27yxt4/DIgvsWyurx9ieEkf4MQkJiWnlj2DOFsIIN4K5OBAcB0xKqWjPGVxLZGUKk5PMOSofXDxtR8ljShOx8YUVpdU7ioiTcAvRCC0YuSDbu6If2ZpiVJ7uLyihpF3ugtMwSXtyIRMG9RS4gp3WwOQ5lzMJR8bKN92L3CLmFEMifZZEje00lbk/D6cIdU3K4Gpg0UZz/+6LEPIgPlR49RAJqInNuqBwI1SneKXi4rdD7wx2RyouRGDoebZs53ODSCG614hPBfvu7i9GJ1fkSBpdbY+8jo1mJlRUOGlOzMWCma4AL7SJ8B6ZozwpFm6u+bARhX5tKqViE+o5o0LmfkgmUqiruya80KEZyiQKMxTabBO70iXcUXqKejV8on0w/Mc+Jndg0/kLtCb+0FbxC0+l1efm/6A2+giNJJqJSUJ/x4yI6KA7kz3BQPf8dBKiwJSsl0Ro8W/ogvk984pr0U9HWgv+kmlSJDtt/XVfCC1cASRzN56FUHr3rOchmCU+kFvm1Dgs6QBbUw8Xs2JQDB8Ozh4iByO6hw42r3uT99otQBdHRU=
  on:
    repo: danog/video-dl
    branch: npm
