language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
before_script:
  - "npm install -g grunt-cli"
  # Narwhal uses a hardcoded path to openjdk v6, so use that version
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq openjdk-6-jre"
  - "PACKAGE=rhino1.7.6; wget https://github.com/mozilla/rhino/releases/download/Rhino1_7_6_RELEASE/$PACKAGE.zip && sudo unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip"
  - "PACKAGE=rhino1.7.6; echo -e '#!/bin/sh\\njava -jar /opt/'$PACKAGE'/js.jar $@' | sudo tee /usr/local/bin/rhino && sudo chmod +x /usr/local/bin/rhino"
  - "PACKAGE=ringojs-0.11; wget https://github.com/ringo/ringojs/releases/download/v0.11.0/$PACKAGE.zip && sudo unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip"
  - "PACKAGE=ringojs-0.11; sudo ln -s /opt/$PACKAGE/bin/ringo /usr/local/bin/ringo && sudo chmod +x /usr/local/bin/ringo"
  - "PACKAGE=v0.3.2; wget https://github.com/280north/narwhal/archive/$PACKAGE.zip && sudo unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip"
  - "PACKAGE=narwhal-0.3.2; sudo ln -s /opt/$PACKAGE/bin/narwhal /usr/local/bin/narwhal && sudo chmod +x /usr/local/bin/narwhal"
  # If the enviroment stores rt.jar in a different directory, find it and symlink the directory
  - "PREFIX=/usr/lib/jvm; if [ ! -d $PREFIX/java-6-openjdk ]; then for d in $PREFIX/java-6-openjdk-*; do if [ -e $d/jre/lib/rt.jar ]; then sudo ln -s $d $PREFIX/java-6-openjdk; break; fi; done; fi"
script:
  - "grunt ci"
after_script:
  - "grunt shell:cover-codecov"
deploy:
  provider: npm
  email: daniil.gentili.dg@gmail.com
  api_key:
    secure: pM4pKTQEJAFEoqi00Ew2g246Yv7/3M+bl0KFl2BOyjvwASPS7c1ZdYqkQxSb0QaqeYjVuBQ9sbioOGU7hQ5IDNuDF861upV5gUn0Mw0iJq3K5mrTctYBCH/og6fLB2UCsR5nvriQCBysHggyQcxbt0OKyaQk+4cfN9+vPmlU093UD25Hq0sbHGadp6dWANTtJxV/jenj2gAWPN0m10I9W2zZlajSa8KB6+nZxcTo+wRUUpU5QqY0TpcxIe0sN/M9lS4s4iJhl3NyUnkvb7rjFFfoG0hq/oMpAhRAaCa08H+18iLd2mP2R8fN0nlNHuiIPvSAoFlE/DcZO4HyCN+FeC2k+ly/SEHtLVxo9fDs63DZDoQmtNSvDXAM74vAd2Lcu82C6tgfn6S1fagRTrjbWfvAQfpczUPb0oCfoi5v+hJ2ENID2A0H1JDER80Im7ih3Ec9N1RvNlCCDg9ZZKXQ6On6JZI2igYq2Tu6lE3kU2q7op4y83UJ9COmg+cpqUHlJAc3oiosxUSqvPf9GsEj2GgFQwMA1aCj0e4G02kEZ4+5DVVjoZQgHnunYnv4Rm46jgudrKXkfjI+GcTKXZ0kQCUzJMuClR8oKxPKKh7krdeAVNR8n2Bi93TS8j6RCP/mvEkBngu3DfUvhbOYEskvj2qxeenwBXm4W8mG0eB7rZ4=
  on:
    repo: danog/video-dl
    branch: npm
